### ISSUE TITLE
Doku?

### ISSUE THREAD

**Issue by k-webdesign** [heimrichhannot-contao-components/masonry#1]
Hi,

installiert hab ich es erfolgreich, aber wie wende ich das jetzt genau an? Gibts eine Doku?

**Comment by koertho** [comment]
Die Einbindung ist in der Readme erklärt, die Dokumentation zur Anwendung findet sich in der Masonry Doku, welche ebenfalls in der Readme verlinkt ist. Dieses Repository dient nur dazu, das sich die Masonry library mit Composer in den Contao assets-Ordner installieren lässt.
